# Generated by Django 5.0.9 on 2024-11-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('permissions', models.ManyToManyField(to='auth.permission')),
            ],
            options={
                'permissions': [('basic', 'Basic p'), ('pro', 'Pro Perm'), ('advanced', 'Advanced Perm')],
            },
        ),
    ]
